In [1]:
import numpy as np

In [2]:
my_house = np.array([18.0, 20.0, 10.75, 9.50])

In [4]:
my_house

array([18.  , 20.  , 10.75,  9.5 ])

In [5]:
your_house = np.array([14.0, 24.0, 14.25, 9.0])

In [7]:
your_house

array([14.  , 24.  , 14.25,  9.  ])

In [16]:
x = np.logical_or( (my_house > 18.5), 
                   (my_house < 10) )

In [18]:
print (your_house[x])

[24.  9.]


In [27]:
y = np.logical_and( (my_house < 11),
                    (your_house < 11) )

In [28]:
y

array([False, False, False,  True])

In [29]:
print (y)

[False False False  True]


In [24]:
print (your_house[y])

[14.25  9.  ]
