In [1]:
x = ['c', 'a', 'b', 'b', 'a', 'c', 'b', 'c']

In [3]:
x

['c', 'a', 'b', 'b', 'a', 'c', 'b', 'c']

In [6]:
x.count('a')

2

In [8]:
import numpy as np
x = np.array([3, 4, False, True, 5.2])
print(x)

[3.  4.  0.  1.  5.2]


In [10]:
import numpy as np
x = np.array([29, 3, 15, 11])
y = np.array([9, 19, 14, 22])

In [15]:
z = np.column_stack([x, y])

In [16]:
print(z.shape)

(4, 2)


In [17]:
z

array([[29,  9],
       [ 3, 19],
       [15, 14],
       [11, 22]])

In [18]:
np.array([x, y])

array([[29,  3, 15, 11],
       [ 9, 19, 14, 22]])

In [19]:
p = False
print(type(p))

<class 'bool'>


In [20]:
p = 6.87705

In [23]:
print(round(p))

7


In [24]:
x = [7, 19, 16, 18, 19, 8]
print(x[0:4])

[7, 19, 16, 18]
