In [53]:
import random
import numpy as np
import pdb

In [37]:
def initialize(p_zero, N):
    # draw the intersection map, NxN adjacency matrix
    # X_ij = amount of time to get from position i to j
    # N: number of intersections
    
    the_map = np.zeros((N,N), dtype=int)
    
    for i in range(0, N):
        for j in range(0, i):
            if random.random() > p_zero:
                the_map[i][j] = random.random() * 100
                the_map[j][i] = the_map[i][j]
        
    return the_map

In [40]:
initialize(p_zero=0, N=10)

array([[ 0, 75, 15, 48, 13, 53, 41, 43,  9, 64],
       [75,  0, 58, 37, 69, 68,  7, 63, 31, 75],
       [15, 58,  0, 33,  5, 46, 57, 60, 32, 35],
       [48, 37, 33,  0, 89, 76, 17, 26, 58, 89],
       [13, 69,  5, 89,  0, 57, 70,  8, 34, 75],
       [53, 68, 46, 76, 57,  0, 17, 84, 18, 26],
       [41,  7, 57, 17, 70, 17,  0, 49, 92, 63],
       [43, 63, 60, 26,  8, 84, 49,  0, 86, 79],
       [ 9, 31, 32, 58, 34, 18, 92, 86,  0, 53],
       [64, 75, 35, 89, 75, 26, 63, 79, 53,  0]])

In [84]:
def fitness(member, the_map):
    # calculate the distance of a route
    pdb.set_trace()
    score = 0
    
    for i in range(1, len(route)):
        if (the_map[route[i-1]][route[i]] == 0) and i != len(the_map)-1:
            print("WARNING: INVALID ROUTE")
            print(route)
            print(the_map)
        score = score + the_map[route[i-1]][route[i]]

    return score

In [85]:
the_map = initialize(p_zero=0, N=10)
the_map
fitness(member=create_new_member(the_map), the_map= the_map)

[0 9]
> <ipython-input-84-a8f080c03ca2>(4)fitness()
-> score = 0
(Pdb) l
  1  	def fitness(member, the_map):
  2  	    # calculate the distance of a route
  3  	    pdb.set_trace()
  4  ->	    score = 0
  5  	
  6  	    for i in range(1, len(route)):
  7  	        if (the_map[route[i-1]][route[i]] == 0) and i != len(the_map)-1:
  8  	            print("WARNING: INVALID ROUTE")
  9  	            print(route)
 10  	            print(the_map)
 11  	        score = score + the_map[route[i-1]][route[i]]
(Pdb) n
> <ipython-input-84-a8f080c03ca2>(6)fitness()
-> for i in range(1, len(route)):
(Pdb) l
  1  	def fitness(member, the_map):
  2  	    # calculate the distance of a route
  3  	    pdb.set_trace()
  4  	    score = 0
  5  	
  6  ->	    for i in range(1, len(route)):
  7  	        if (the_map[route[i-1]][route[i]] == 0) and i != len(the_map)-1:
  8  	            print("WARNING: INVALID ROUTE")
  9  	            print(route)
 10  	            print(the_map)
 11  	        score = score +

BdbQuit: 

In [2]:
def crossover(a, b):
    # breed mix solutions
    return a

In [3]:
def mutate(member):
    return member

In [56]:
def create_new_member(the_map):
    #pdb.set_trace()
    # creating route randomly
    # route structure will be a vector of integers where each value is the enxt step in the route
    # we need to go from 0 to end value and not pass zero's
    N = len(the_map)
       
    route = np.zeros(1, dtype=int)
    go = True
    i = 1

    while go:
        possible_values = np.nonzero(the_map[route[i-1]])
        proposed_value = random.randint(0, len(possible_values[0])-1)
        route = np.append(route, possible_values[0][proposed_value])
            
        if route[i] == N-1:
            go = False
        else:
            i += 1

    print(route)    
    return route

In [57]:
the_map = initialize(p_zero=0, N=10)
the_map

array([[ 0, 80, 62,  8, 38, 54, 65,  3, 61, 96],
       [80,  0, 93, 63, 39, 29, 68, 90,  1, 95],
       [62, 93,  0, 83,  2, 43, 15, 45, 77, 76],
       [ 8, 63, 83,  0, 53, 42, 76, 52, 92, 16],
       [38, 39,  2, 53,  0, 46, 41, 49, 75, 10],
       [54, 29, 43, 42, 46,  0, 32, 55, 65, 49],
       [65, 68, 15, 76, 41, 32,  0, 41, 99,  7],
       [ 3, 90, 45, 52, 49, 55, 41,  0, 18, 45],
       [61,  1, 77, 92, 75, 65, 99, 18,  0, 83],
       [96, 95, 76, 16, 10, 49,  7, 45, 83,  0]])

In [72]:
create_new_member(the_map)

[0 2 3 5 6 4 6 9]


array([0, 2, 3, 5, 6, 4, 6, 9])

In [6]:
def create_next_generation(population):
    return population

In [ ]:
def main(number_of _iterations):
    return True